import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import AppProvider from "@/providers/AppProvider";
import Navbar from "@/components/shared/Navbar/Navbar";
import AuthProvider from "@/providers/AuthProvider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "hevias_footwear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(dmSans.className, "antialiased bg-[#f2f1f0]")}>
        <AuthProvider>
          <AppProvider>
            <header>
              <Navbar />
            </header>
            {children}
          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
